# -include .env
#
# .PHONY: to test deploy
#
# help: 
# 	@echo "Usage:"
# 	@echo " make deploy [ARGS=...]"
#
# build:
# 	forge build
#
# install:;
# 	forge install chainaccelorg/foundry-devops --no-commit && forge install smartcontractkit/chainlink-brownie-contract --no-commit &&
# forge install foundry-rs/forge-std --no-commit && 
# 	forge instlal transmissions11/solmate --no-commit
#
# testlocalchain:
# 	forge test -vvv
#
# #to check make the network args based on the chain 
# ifeq($(findstring onSepolia,$(ARGS)),onSepolia)
# 	NETWORK_ARGS := --rpc-url $(RPC_URL_SEPOLIA) --private-key $(PRIVATE_KEY_SEPOLIA) --broadcast --verify --etherscan-api-key $(EHTERSCAN_APIKEY)
# 	-vvvv
# endif
#
# deploy: 
# 	forge script script/DeployRaffle.s.sol:DeployRaffle
